In [3]:
class Node:
    def __init__(self, item=None, link=None):
        self.item = item
        self.link = link
        
a = Node('사과')
print(a)
print(a.item)
print(a.link)

b = Node('바나나', a)
print(b)
print(b.item)
print(b.link.item)

사과
None
바나나
사과


### Single Linked List
- append(item) : 리스트 맨 뒤 item 노드 추가
- insert(k, item) : k번째 위치에 item 새 노드 삽입
- delete(item) : item 위치 노드 제거
- find(item) : item 위치 리턴
- print() : 리스트 내 모든 item 출력

In [4]:
class LinkedList:
    def __init__(self):
        self.root = None

    def append(self, item):
        if self.root == None:
            self.root = Node(item)
        else:
            curNode = self.root
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = Node(item)
    
    def insert(self, k, item):
        if k == 0:
            _tmp = self.root
            self.root = Node(item)
            self.root.link = _tmp
        else:
            curNode = self.root
            # k번째 자리에 넣는 함수이므로, k-1의 링크와 연결
            for i in range(k-1):
                curNode = curNode.link
            _tmp = curNode.link
            newNode = Node(item)
            curNode.link = newNode
            newNode.link = _tmp
    
    def find(self, item):
        curNode = self.root
        k = 0
        if curNode.item == item:
            return 0
        else:
            while curNode.link != None:
                curNode = curNode.link
                k += 1
                if curNode.item == item:
                    return k
                
    def delete(self, item):
        k = self.find(item)
        if k == 0:
            self.root = self.root.link
        else:
            curNode = self.root
            # k번째 node 삭제하는 것이므로, k-1번째에서 연결 고리를 끊는 방식
            for i in range(k-1):
                curNode = curNode.link
            curNode.link = curNode.link.link
    
    def print(self):
        curNode = self.root
        while curNode.link != None:
            print(curNode.item, end=' -> ')
            curNode = curNode.link
        print(curNode.item)

example

In [5]:
fruits = LinkedList()
# append
fruits.append('grape')
fruits.append('apple')
fruits.append('banana')
fruits.print()

grape -> apple -> banana


응용문제 : 다항식 덧셈

In [ ]:
import copy
class Poly1:
    def __init__(self, order):
        self.order = order
        self.coef = [0] * (order+1)

    def set_coef(self, coef, order):    # 계수 세팅
        self.coef[order] = coef


    # 가장 큰 차수의 값을 보여주는 함수
    def peek(self):
        return self.coef[-1]

    #pop하는 함수
    def pop(self):
        return self.coef.pop(-1)

    # 객체 자신에 대한 세팅을 하기 때문에 staticmethod
    @staticmethod
    def add(p, q):

        # r : p와 q 중 가장 큰 차수를 가진 빈 리스트를 만듦
        r = Poly1(max(p.order, q.order))

        # 그 빈 리스트에 더하는 처리
        for i in range(max(len(p.coef), len(q.coef))):
            if i >= len(p.coef):
                r.coef[i] = q.coef[i]
            elif i >= len(q.coef):
                r.coef[i] = p.coef[i]
            else:
                r.coef[i] = p.coef[i] + q.coef[i]

        return r


# 실행
p = Poly1(4)        # input : 몇 차항인지
p.set_coef(4, 4)    # input : 어느 차수에 무슨 숫자가 들어가는지
p.set_coef(3,2)
p.set_coef(3,0)
print(p.coef)

# q 빈 리스트 객체 생성
q = Poly1(3)
# q 리스트에 다항식 계수 입력
q.set_coef(3,3)
q.set_coef(4,2)
q.set_coef(2,1)
q.set_coef(1,0)
# 다항식 확인
print(q.coef)

# 두 개의 다항식 덧셈 연산
new_poly = Poly1.add(p, q)
print(new_poly.coef)



[3, 0, 3, 0, 4]
[1, 2, 4, 3]
[4, 2, 7, 3, 4]


In [9]:
class Poly2:
    def __init__(self):
        self.coef = []
    def set_coef(self, coef, order):
        self.coef.append([coef, order])

    def get_max_order(self):
        if len(self.coef) == 0:# 리스트 크기가 업으면, empty라는 것을 의미함.
            return -1
        return self.coef[0][1]

    def pop(self): # 뽑는 함수
        if len(self.coef) == 0: # empty의 경우,
            return None # 타입을 맞춰주는 것. 리스트가 없으니 None이라고 하자.
        return self.coef.pop(0)

    @staticmethod
    def add(_p, _q): # 두개의 폴리 객체를 받아 더하는 함수
        p = copy.deepcopy(_p)
        q = copy.deepcopy(_q)

        r = Poly2() # 결과를 담을 새로운 객체 생성

        while p.get_max_order() > -1 and q.get_max_order() > -1:
            if p.get_max_order() > q.get_max_order(): # p의 차수가 더 큰 경우, p에서 가져와야함.
                _tmp = p.pop()
                r.set_coef(_tmp[0], _tmp[1])
            elif q.get_max_order() > p.get_max_order(): # p의 차수가 더 큰 경우, p에서 가져와야함.
                _tmp = q.pop()
                r.set_coef(_tmp[0], _tmp[1])
            else: # 두 개 팝해야 함.
                _tmp1 = p.pop()
                _tmp2 = q.pop()
                if _tmp1[0] + _tmp2[0] != 0:
                    r.set_coef(_tmp1[0] + _tmp2[0], _tmp1[1]) #order는 같아서 들어온 것이므로 tmp1,2 상관없음.

            # 잔여 항 처리
            while p.get_max_order() > -1: # empty인 경우는 와일문이 안 돈다.
                _tmp = p.pop()
                r.set_coef(_tmp[0], _tmp[1])
            while q.get_max_order() > -1: # empty인 경우는 와일문이 안 돈다.
                _tmp = q.pop()
                r.set_coef(_tmp[0], _tmp[1])
            return r

k = Poly2() # 객체 생성
k.set_coef(4,4)
k.set_coef(3,2)
k.set_coef(3,0)
print(k.coef)

j = Poly2() # 객체 생성
j.set_coef(3,3)
j.set_coef(3,3)
j.set_coef(3,3)

r = Poly2.add(k,j)
print("POLY2")
print(k.coef, j.coef, r.coef)

[[4, 4], [3, 2], [3, 0]]
POLY2
[[4, 4], [3, 2], [3, 0]] [[3, 3], [3, 3], [3, 3]] [[4, 4], [3, 2], [3, 0], [3, 3], [3, 3], [3, 3]]


exam 2 : SparseMatrix

In [7]:
import numpy as np

'''
tip: 컴퓨터는 1차원 배열만 있음.
SparseMatrix 자료구조
1. 행렬의 dimension m, n을 입력받아 희소행렬 리스트를 [[m,n,0]]로 초기 설정한다.
2. append method: [i, j, value] 형태의 리스트를 희소 행렬 리스트에 추가한다.
3. shape method: 희소행렬 dimension을 리턴한다.
4. getValue method : i, j 행렬 값을 리턴
5. print method : 희소 행렬을 일반적으로 행렬 형태로 프린트(0으로 구성된 m,n array를 만들고 i,j행렬 값 업데이트)

희소행렬의 전치행렬 알고리즘 : 희소행렬의 행 [i,j,value] -> [j,i,value]로 변환

두 희소행렬의 덧셈 알고리즘
1. 덧셈 결과를 저장할 빈 희소행렬 c만듦
2. 두 희소행렬 a, b의 unique한 (i,j) 쌍의 집합을 u라고 하자.
3. u에서 원소를 하나씩 꺼내면서 a, b해당 위치 값을 구해 더한다.
4. 위에서 구한 값이 0이 아니면 c에 추가한다.
'''
class SparseMatrix:
    def __init__(self, m, n):# m by n인지 정함
        self.s = [[m,n,0]] # header이다.

    # 추가하는 함수
    def append(self, i, j, value):
        self.s.append([i, j, value])
        self.s[0][2] += 1 # append를 완료하면 초기 0으로 설정했던 value값을 1추가하는 작업.

    # 행렬의 shape:Dimension을 반환. (n by m)
    def shape(self):
        return self.s[0][0], self.s[0][1]

    # 원하는 i by j 위치에 맞는 값 반환 받는 함수
    def get_value(self, ii, jj):
        for idx in range(1, len(self.s)): # header는 어차피 [n, m, 0]이므로 헤더 제외한 다음부터.
            if self.s[idx][0] == ii  and self.s[idx][1] == jj:
                # 왜 ii, jj가 되는 거지?
                """
                행렬의 모양은 [[i, j, value]] 이 모양으로 저장하게 되는데,
                i번째 행렬에서 0번째 인덱스니까 저 위치에는 i.
                i번재 행렬에서 1번째 인덱스니까 저 위치에는 j.
                각 위치에 i와 j가 맞는지 확인하는 반복문과 조건문인 것이다.
                """
                return self.s[idx][2] # value값 반환
        return 0 # 다 돌았는데 없다고 한다면 "0"를 반환해라

    def print_matrix(self):
        x = np.zeros(self.shape()) # numpy로 self와 같은 차원을 가진 영행렬 생성
        # 생성한 영행렬에 기존 저장되어 있던 행렬을 저장
        for i in range(1, len(self.s)):
            x[self.s[i][0], self.s[i][1]] = int(self.s[i][2]) # [[행, 열, 값]] 0:행, 1:열, 2:값
        print(x)
        return x
    @staticmethod
    # 전치
    # 이거 잘 모르겠다.
    def transpose(x):# 원본은 그대로 두기 위해 새로운 변수 s1생성.
        x_t = SparseMatrix(x.s[0][1], x.s[0][0]) # m by n인 배열을 만들어라. i,j = j,i로 순서 변경하기 위해 [0][1], [0][0]
        x_t.s = x.s[:] # deep copy

        for i in range(len(x.s)):
            x_t.s[i][0], x_t.s[i][1] = x_t.s[i][1], x_t.s[i][0] # a,b=b,a
        return x_t

#    두 희소행렬의 덧셈 알고리즘
#1. 덧셈 결과를 저장할 빈 희소행렬 c만듦
#2. 두 희소행렬 a, b의 unique한 (i,j) 쌍:주소의 집합을 u라고 하자.
#3. u에서 원소를 하나씩 꺼내면서 a, b해당 위치 값을 구해 더한다.
#4. 위에서 구한 값이 0이 아니면 c에 추가한다.

    def add(x, y):
        c = SparseMatrix(x.shape()[0], x.shape()[1])
        u = set()  #unique(i, j)의 합집합.
        for i in range(1,len(x.s)):
            u.add((x.s[i][0], x.s[i][1]))
        for i in range(1,len(y.s)):
            u.add((y.s[i][0], y.s[i][1]))
        for _u in u:
            _tmp1 = x.get_value(_u[0], _u[1])
            _tmp2 = y.get_value(_u[0], _u[1])
            if _tmp1 + _tmp2 != 0:
                c.append(_u[0], _u[1], _tmp1+_tmp2)
        return c

#두 희소 행렬 곱셈 수행하는 함수 작성
#1. 두 행렬의 곱셈은 A는 r by c, B는 c by l과 같이 A의 열의 수와 B의 행수가 같아야 함
#아니면 null리턴. 곱셈결과 c행렬은 r by l이 된다.
#2. 희소행렬 곱셈 결과를 저장할 빈 리스트 생성
#3. 위의 식 Cij를 계산해서 그 값이 0 이 아니면 C희소행렬에 추가
#4. C희소행렬에 add한 개수와 결과 dimension을 계산한 후, 헤더를 업데이트 한다.
#5. C희소행렬을 반환한다.

    @staticmethod
    def mul(a, b):
        # 1. 두 행렬의 곱셈에서 a의 열 == b의 행이 같아야 한다.
        if a.shape()[1] != b.shape()[0]:
            return None

        # 2. 곱셈 결과를 저장할 행렬 c 생성
        c = SparseMatrix(a.shape()[0], b.shape()[1])

        # 3. a 행렬의 각 원소를 순회
        for i in range(1, len(a.s)):
            ai, aj, av = a.s[i]  # a의 i번째 원소 ai, aj는 위치, av는 값
            # 4. b 행렬에서 aj(=a열)에 해당하는 행의 원소를 찾음
            for j in range(1, len(b.s)):
                bi, bj, bv = b.s[j]
                if bi == aj:  # b의 행이 a의 열과 같은 경우
                    if (av * bv) != 0: # 0 이 아닌 경우만 추가하는 조건문
                        c.append(ai, bj, av * bv)
        return c

    def print_sparse(self):
        # 1. 희소 행렬의 저장된 값들을 출력 (헤더 제외)
        for i in range(1, len(self.s)):
            print(f"({self.s[i][0]}, {self.s[i][1]}) : {self.s[i][2]}")


# 테스트 예시
a = SparseMatrix(3, 3)
a.append(0, 1, 3)
a.append(1, 0, 2)
a.append(2, 2, 1)

b = SparseMatrix(3, 3)
b.append(0, 1, 4)
b.append(1, 2, 5)
b.append(2, 0, 6)

a.print_matrix()
b.print_matrix()

# 결과 출력
c = SparseMatrix.mul(a, b)
print(c.print_matrix())
c.print_sparse()


[[0. 3. 0.]
 [2. 0. 0.]
 [0. 0. 1.]]
[[0. 4. 0.]
 [0. 0. 5.]
 [6. 0. 0.]]
[[ 0.  0. 15.]
 [ 0.  8.  0.]
 [ 6.  0.  0.]]
[[ 0.  0. 15.]
 [ 0.  8.  0.]
 [ 6.  0.  0.]]
(0, 2) : 15
(1, 1) : 8
(2, 0) : 6
